---
- hosts: localhost
  become: yes
  vars_files:
    # This file not included in Git
    - secret_vars/local_network.yml
  roles:
    - network
    - system
    - devtools
    - productivity
    - misc
    - xorg
    - multimedia
