---
- name: Install xorg config files
  copy:
    src: xorg_config/
    dest: /etc/X11/xorg.conf.d/

- name: Install xorg and desktop environment things
  package:
    name:
      # server and drivers
      - xorg-server
      - xf86-video-amdgpu
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - vulkan-radeon
      - lib32-vulkan-radeon
      # login manager
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings
      # desktop things
      - light-locker
      - gnome-screensaver
      - xfce4
      - xfce4-goodies
    state:
      present

- name: Enable and start lightdm service
  service:
    name: lightdm
    state: started
    enabled: yes
