---
- name: Configure initramfs
  copy:
    dest: /etc/
    src: mkinitcpio.conf
  register: mkinitcpio_conf

- name: Rebuild initramfs
  command: mkinitcpio -g /boot/initramfs-linux.img
  when: mkinitcpio_conf.changed

- name: Enable multilib in pacman.conf
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Set make job count
  set_fact:
    make_job_count: "{{ [1, (ansible_processor_vcpus * 0.8) | int] | max }}"

- name: Set MAKEFLAGS for makepkg
  lineinfile:
    path: /etc/makepkg.conf
    regexp: '^#?MAKEFLAGS='
    line: 'MAKEFLAGS="-j{{ make_job_count }}"'
