---
- name: Enable multilib in pacman.conf
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Set MAKEFLAGS for makepkg
  lineinfile:
    path: /etc/makepkg.conf
    regexp: '^#?MAKEFLAGS='
    line: 'MAKEFLAGS="-j{{ (ansible_processor_vcpus * 0.8) | int }}"'
