---
- name: Configure initramfs
  copy:
    dest: /etc/
    src: mkinitcpio.conf
  notify:
    - Rebuild initramfs

- name: Enable multilib in pacman.conf
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Set job count
  set_fact:
    job_count: "{{ [1, (ansible_processor_vcpus * 0.8) | int] | max }}"

- name: Enable parallelism for jobs in makepkg
  lineinfile:
    path: /etc/makepkg.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^#?MAKEFLAGS=', line: 'MAKEFLAGS="-j{{ job_count }}"' }
    - { regexp: '^#?COMPRESSXZ=', line: 'COMPRESSXZ=(xz -c -z -T{{ job_count }} -)' }
