---
- name: Install network software
  package:
    name:
      - openssh
      - rsync
      - mosh
      - wget
      - openntpd

- name: Install sshd config file
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config

- name: Create /root/.ssh
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700

# This is so the file server can log in and pull backups
- name: Install authorized_keys for root
  copy:
    dest: /root/.ssh/authorized_keys
    content: "{{ root_authorized_keys }}"
    owner: root
    group: root
    mode: 0600

- name: Install ntpd.conf
  copy:
    dest: /etc/ntpd.conf
    src: ntpd.conf

- name: Enable network services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - systemd-networkd.service
    - dhcpcd.service
    - sshd.socket
    - openntpd.service

- name: Install nfs-utils
  package:
    name: nfs-utils
    state: present

- name: "Mount NFS share from {{ lan_file_server }}"
  mount:
    src: "{{ lan_file_server }}:/storage"
    path: /storage
    fstype: nfs4
    opts: _netdev,auto,soft
    state: mounted
