---
- name: Install miscellaneous utility software
  package:
    name:
      # browsers
      - firefox
      - chromium

      - htop
      - redshift
      - jre-openjdk
      - transmission-gtk
      - ttf-dejavu

      - pixz
      - pigz
      - file-roller
      - unrar
      - cdrtools

      - gvfs
      - gvfs-mtp
    state: present

- name: Install lib32 packages
  package:
    name:
      - lib32-libpulse
      - lib32-util-linux
    state: present
