---
- name: Install miscellaneous utility software
  package:
    name:
      # browsers
      - firefox
      - chromium

      # remote connections
      - openssh
      - mosh
      - wget

      - redshift
      - jre-openjdk
      - transmission-gtk
      - ttf-dejavu
    state: present
